### ISSUE TITLE
作業済みのelements一覧

### ISSUE THREAD

**Issue by geckotang** [webcre8/html5style#32]
作業が完了したらチェックを入れる。
作業中の場合でも該当のissue番号は入れる。
コミットログに #32 を含めると、このページに出るのでわかりやすいかも？
- [x] h1(見出し、h2〜h6も同じページで扱う) #14 
- [x] p(段落) #17 
- [x] hr(水平線) #21 
- [x] pre(整形テキスト) #23 
- [x] blockquote(引用ブロック、citeを含む) #30 
- [x] address(連絡先情報) #26 
- [x] ol(序列リスト、liを含む) #18 
- [x] ul(非序列リスト、liを含む) #19 
- [x] dl(対応リスト、dt、ddを含む) #33 
- [x] figure(補足コンテンツ、figcaptionを含む) #31 
- [x] table(テーブル、tr、th、td、thead、tfoot、tbody、caption、col、colgroupを含む) #34
- [x] b(役割の異なるフレーズ) #49
- [x] i(意味の異なるフレーズ) #37
- [ ] a(ハイパーリンク)
- [x] em(語気を強めるフレーズ) #39
- [x] strong(重要性の高いフレーズ) #45
- [ ] small(注釈)
- [x] s(打ち消し線のフレーズ) #48 
- [ ] cite(題名のフレーズ)
- [ ] q(引用のフレーズ)
- [ ] dfn(定義のフレーズ)
- [x] abbr(略称のフレーズ) #47
- [x] time(時刻のフレーズ) #44
- [ ] code(コードのフレーズ)
- [x] var(変数のフレーズ) #46
- [ ] samp(出力結果のフレーズ)
- [ ] kbd(キーボード入力のフレーズ)
- [ ] sup(上付き文字のフレーズ)
- [ ] sub(下付き文字のフレーズ)
- [ ] u(スペルミスや特殊な扱いのフレーズ)
- [ ] mark(目印のついたフレーズ)
- [ ] ruby(ルビ付きのフレーズ、rb、rp、rt、rtcを含む)
- [ ] bdo(文書方向に関するフレーズ、bdiも同じページで扱う)
- [ ] img(画像)
- [x] ins(挿入コンテンツ) #24 
- [x] del(削除コンテンツ) #25
- [ ] fieldset(フォームのグルーピング、legendを含む)
- [ ] input(入力項目、label、datalistを含む)
- [ ] select(選択入力、optgroup、optionを含む)
- [ ] button(ボタン)
- [ ] textarea(文章入力)
- [ ] keygen(暗号選択入力)
- [ ] output(出力情報)
- [ ] progress(進捗状況)
- [ ] meter(割合を表す)

**Comment by oti** [comment]
@webcre8 セクショニング・コンテンツやform要素も入れるっていうのは合意でいいのかな。合意ならチェックリストしましょう。
